- type: replace
  path: /releases?/name=networking?
  value:
    name: networking
    sha1: 9b5f9d27917c3754e492470ac6c9af80d62963db
    url: http://bosh.io/d/github.com/cloudfoundry/networking-release?v=9
    version: 9