---
meta:
  default:
    azs: [z1]

params:
  hostname: (( concat params.env "-jumpbox" ))
  banner: ~
  hosts: []
  env_vars: {}
  bashrc: ~
  users: (( param "Set up some users to log into this jumpbox" ))

update:
  canaries: 1
  max_in_flight: 4
  canary_watch_time: 1000-60000
  update_watch_time: 1000-60000
  serial: false

instance_groups:
  - name: jumpbox
    instances: 1
    azs: (( grab params.availability_zones || meta.default.azs ))
    persistent_disk_type: (( grab params.jumpbox_disk_pool || "jumpbox" ))
    vm_type:              (( grab params.jumpbox_vm_type   || "jumpbox" ))
    stemcell: default
    networks:
      - name: (( grab params.jumpbox_network || "jumpbox"))
        static_ips: (( static_ips 0 ))
    jobs:
      - { release: jumpbox, name: jumpbox         }
      - { release: jumpbox, name: inventory       }
      - { release: toolbelt, name: toolbelt       }
      - { release: toolbelt, name: toolbelt-quick }

properties:
  jumpbox:
    hostname: (( grab params.hostname ))
    users: (( grab params.users ))
    env:
      TMPDIR: /var/vcap/data/root_tmp
      .: (( inject params.env_vars ))

stemcells:
  - alias: default
    os:      (( grab params.stemcell_os      || "ubuntu-xenial" ))
    version: (( grab params.stemcell_version || "latest" ))

releases:
- name:    jumpbox
  version: 4.6.2
  url:     https://github.com/cloudfoundry-community/jumpbox-boshrelease/releases/download/v4.6.2/jumpbox-4.6.2.tgz
  sha1:    7a5b68669a1ee5a120a7638809576d92d05cd93c

- name:    toolbelt
  version: 3.4.4
  url:     https://github.com/cloudfoundry-community/toolbelt-boshrelease/releases/download/v3.4.4/toolbelt-3.4.4.tgz
  sha1:    40cb5831cba1dc52bbf447e17b795a59504d51e2
